#! /bin/sh
### BEGIN INIT INFO
# Provides:			iperf3
# Required-Start:	$remote_fs $syslog
# Required-Stop:	$remote_fs $syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Execute the xterminal_broker command.
# Description:
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

IPERF3=/var/run/iperf3.pid
PORT=3389

do_start () {
	start-stop-daemon --start --make-pidfile --pidfile $IPERF3 --background --exec /usr/bin/iperf3 -- -s -p $PORT 
	start-stop-daemon --start --make-pidfile --pidfile /var/run/bondx.pid --background --exec /usr/bin/bondx 
}

do_stop () {
	start-stop-daemon --stop --pidfile $IPERF3
	start-stop-daemon --stop --pidfile /var/run/bondx.pid
	sleep 1
	rm -f $IPERF3
	rm -f /var/run/bondx.pid
}

case "$1" in
  start)
	do_start
	;;
  stop)
	do_stop
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  status)
	exit 0
	;;
  *)
	echo "Usage: $0 start|stop" >&2
	exit 3
	;;
esac

