#!/bin/sh

### BEGIN INIT INFO
# Provides:        ss-server
# Required-Start:  $network $remote_fs $syslog
# Required-Stop:   $network $remote_fs $syslog
# Default-Start:   2 3 4 5
# Default-Stop: 
# Short-Description: Start ss-server daemon
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin

. /lib/lsb/init-functions

DAEMON=/bin/ss-server
PIDFILE=/var/run/ss.pid

test -x $DAEMON || exit 5
case $1 in
	start)
		start-stop-daemon  --start --background --make-pidfile $PIDFILE  --quiet  --pidfile $PIDFILE --exec $DAEMON -- -c /etc/config.json 
  		;;
	stop)
		start-stop-daemon  --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --exec $DAEMON
  		;;
	restart)
		$0 stop && sleep 2 && $0 start
  		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 2
		;;
esac
